services:

  server1:
    build: .
    image: ubuntu-ansible
    container_name: server1
    ports:
      - "2201:22"
      - "10001:10000"

  server2:
    build: .
    image: ubuntu-ansible
    container_name: server2
    ports:
      - "2202:22"
      - "10002:10000"

  server3:
    build: .
    image: ubuntu-ansible
    container_name: server3
    ports:
      - "2203:22"
      - "10003:10000"

  server4:
    build: .
    image: ubuntu-ansible
    container_name: server4
    ports:
      - "2204:22"
      - "10004:10000"

  server5:
    build: .
    image: ubuntu-ansible
    container_name: server5
    ports:
      - "2205:22"
      - "10005:10000"